/**
 * Renders the inbox as an xbar/SwiftBar plugin menu.
 *
 * This runs from the menu-bar host's working directory, not from the session
 * that owns the collector — so the session label has to come from /health over
 * the wire. Pending items are read straight off disk, which keeps the menu
 * honest when the collector is down but items are still queued.
 */
import { chmodSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { DEFAULT_PORT, HOST } from './config.mjs'
import { listFeedback, paths } from './store.mjs'

const SELF = process.argv[1]

async function probe(port) {
  try {
    const response = await fetch(`http://${HOST}:${port}/health`, {
      cache: 'no-store',
      signal: AbortSignal.timeout(700),
    })
    if (!response.ok) return undefined
    return await response.json()
  } catch {
    return undefined
  }
}

function line(text, params = {}) {
  const entries = Object.entries(params).filter(([, value]) => value !== undefined)
  const suffix = entries.length === 0 ? '' : ` | ${entries.map(([k, v]) => `${k}=${v}`).join(' ')}`
  // A literal | would be read as the start of xbar's parameter list.
  return `${String(text).replaceAll('|', '¦')}${suffix}`
}

export async function renderMenubar({ port = DEFAULT_PORT } = {}) {
  const health = await probe(port)
  const pending = listFeedback({ status: 'pending', limit: 50 })
  const out = []

  const up = health !== undefined
  const label = up ? (health.session?.label ?? 'tidy') : 'not running'
  out.push(line(pending.length === 0 ? '◔' : `◉ ${pending.length}`, { sfimage: undefined }))
  out.push('---')

  out.push(line(up ? label : 'collector not running', { color: up ? '#34d399' : '#f87171' }))
  if (up) out.push(line('Open setup page', { href: `http://${HOST}:${port}/` }))
  else out.push(line('Start it: tidy serve', { color: '#9ca3af' }))
  out.push('---')

  if (pending.length === 0) {
    out.push(line('No pending feedback', { color: '#9ca3af' }))
  } else {
    out.push(line(`${pending.length} pending`, { color: '#9ca3af' }))
    for (const item of pending) {
      const first = String(item.comment ?? '').split('\n')[0]
      const text = first.length > 60 ? `${first.slice(0, 60)}…` : first
      out.push(line(text))
      out.push(
        line('--Show', {
          bash: SELF,
          param1: 'show',
          param2: item.id,
          terminal: 'true',
        }),
      )
      out.push(
        line('--Resolve', {
          bash: SELF,
          param1: 'resolve',
          param2: item.id,
          terminal: 'false',
          refresh: 'true',
        }),
      )
      const where = item.page?.url
      if (where !== undefined) out.push(line(`--${where}`, { href: where }))
    }
  }

  out.push('---')
  out.push(line('Refresh', { refresh: 'true' }))
  return `${out.join('\n')}\n`
}

/** Writes the shim the menu-bar host actually executes. */
export function installPlugin(dir, { port = DEFAULT_PORT, seconds = 5 } = {}) {
  const file = join(dir, `tidy.${seconds}s.sh`)
  const script = `#!/bin/bash
# tidy — generated by \`tidy menubar --install\`
exec "${process.execPath}" "${SELF}" menubar --port ${port}
`
  writeFileSync(file, script)
  chmodSync(file, 0o755)
  return file
}

export const menubarHelp = `Renders the inbox as an xbar/SwiftBar menu.

  tidy menubar                 Print the menu (this is what the plugin runs)
  tidy menubar --install DIR   Write tidy.5s.sh into your plugin folder

SwiftBar keeps plugins in the folder you chose on first launch; xbar uses
~/Library/Application Support/xbar/plugins. Inbox: ${paths.INBOX}
`
